### ISSUE TITLE
Add gas comparison for ERC4626

### ISSUE THREAD

**Issue by ecivini** [ecivini/gas-bad#2]
Gas comparison for ERC4626 is still marked as TODO.

**Comment by daredevil3435** [comment]
I would like to contribute to this issue. Can you tell how to get started?

**Comment by ecivini** [comment]
Hey, that's great!

First of all you have to write 3 smart contracts that expose all the functions specified in the ERC4626 using OpenZeppelin, Solady and Solmate. After that you have to write the same tests that cover all functions for these 3 smart contracts and do a gas comparison with foundry. Lastly, you have to create a table like the one you see in the README.md, compute the same statistics you see and put them in the table. 

If you have other questions just let me know!
